export const LOGIN_USER_START = 'LOGIN_USER_START';
export const REGISTER_USER_START = 'REGISTER_USERSTART_';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const LOGIN_USER_FAIL = 'LOGIN_USER_FAIL';
export const REGISTER_USER_FAIL = 'REGISTER_USER_FAIL';
